'use client'

import React, { useState } from 'react'
import Link from 'next/link'
import { approveLabReportAction } from '@/actions/laboratory/labOperationsActions'
import { ArrowLeft, ClipboardList, CheckCircle, ExternalLink, User, FlaskConical, TrendingUp, TrendingDown, Minus, AlertTriangle } from 'lucide-react'
import dayjs from 'dayjs'

const FLAG_ICON: Record<string, React.ComponentType<any>> = {
  'Normal': Minus, 'High': TrendingUp, 'Low': TrendingDown, 'Critical': AlertTriangle, 'Abnormal': AlertTriangle
}
const FLAG_COLOR: Record<string, string> = {
  'Normal': 'text-green-600', 'High': 'text-orange-500', 'Low': 'text-blue-500', 'Critical': 'text-red-600', 'Abnormal': 'text-purple-600'
}

export default function ReportViewerClient({ report, currentUserId }: { report: any; currentUserId: string }) {
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const handleApprove = async () => {
    setLoading(true); setError(null)
    const res = await approveLabReportAction(report.id)
    if (!res.success) setError(res.error ?? 'Failed to approve')
    setLoading(false)
  }

  const isDraft = report.report_status === 'Draft'

  return (
    <div className="p-6 max-w-5xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center gap-4">
        <Link href="/laboratory/reports" className="p-2 bg-white border border-slate-200 rounded-lg shadow-sm text-slate-500 hover:text-slate-900 transition">
          <ArrowLeft className="w-5 h-5" />
        </Link>
        <div className="flex-1">
          <div className="flex items-center gap-3">
            <ClipboardList className="w-6 h-6 text-blue-500" />
            <h1 className="text-2xl font-bold text-slate-900 font-mono">{report.report_number}</h1>
            <span className={`px-3 py-1 rounded-full text-xs font-bold ${
              report.report_status === 'Approved' ? 'bg-green-100 text-green-700' : 'bg-amber-100 text-amber-700'
            }`}>{report.report_status}</span>
          </div>
          <p className="text-sm text-slate-500 mt-1">
            {report.lab_order?.patient?.first_name} {report.lab_order?.patient?.last_name} • Order #{report.lab_order?.order_number}
          </p>
        </div>
        <div className="flex gap-2">
          {report.signedUrl && (
            <a href={report.signedUrl} target="_blank" rel="noopener noreferrer"
              className="inline-flex items-center gap-2 bg-slate-100 hover:bg-slate-200 text-slate-700 px-4 py-2 rounded-lg font-semibold text-sm transition">
              <ExternalLink className="w-4 h-4" /> View PDF
            </a>
          )}
          {isDraft && (
            <button onClick={handleApprove} disabled={loading}
              className="inline-flex items-center gap-2 bg-green-600 text-white px-4 py-2 rounded-lg font-semibold hover:bg-green-700 disabled:opacity-50 text-sm">
              <CheckCircle className="w-4 h-4" /> Approve Report
            </button>
          )}
        </div>
      </div>

      {error && <div className="p-3 bg-red-50 border border-red-200 text-red-700 rounded-lg text-sm">{error}</div>}

      {/* Patient & Report Info */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-5 space-y-3">
          <h3 className="font-bold text-slate-800 border-b border-slate-100 pb-3 flex items-center gap-2">
            <User className="w-4 h-4 text-slate-400" /> Patient Information
          </h3>
          <Row label="Name" value={`${report.lab_order?.patient?.first_name} ${report.lab_order?.patient?.last_name}`} />
          <Row label="Gender" value={report.lab_order?.patient?.gender ?? '—'} />
          <Row label="DOB" value={report.lab_order?.patient?.date_of_birth ? dayjs(report.lab_order.patient.date_of_birth).format('DD MMM YYYY') : '—'} />
        </div>
        <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-5 space-y-3">
          <h3 className="font-bold text-slate-800 border-b border-slate-100 pb-3 flex items-center gap-2">
            <ClipboardList className="w-4 h-4 text-slate-400" /> Report Information
          </h3>
          <Row label="Generated" value={dayjs(report.generated_at).format('DD MMM YYYY, h:mm A')} />
          <Row label="Generated By" value={`${report.generator?.first_name ?? ''} ${report.generator?.last_name ?? ''}`.trim() || '—'} />
          {report.approved_at && <Row label="Approved" value={dayjs(report.approved_at).format('DD MMM YYYY, h:mm A')} />}
          {report.approver && <Row label="Approved By" value={`${report.approver.first_name} ${report.approver.last_name}`} />}
        </div>
      </div>

      {/* Test Results */}
      <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
        <div className="px-6 py-4 bg-slate-50 border-b border-slate-200 flex items-center gap-2">
          <FlaskConical className="w-5 h-5 text-blue-500" />
          <h2 className="font-bold text-slate-800">Test Results</h2>
        </div>

        {report.lab_order?.lab_order_items?.map((item: any) => (
          <div key={item.id} className="border-b border-slate-100 last:border-b-0">
            <div className="px-6 py-3 bg-blue-50/40 flex items-center justify-between">
              <p className="font-semibold text-slate-700">{item.test_name}</p>
              <span className={`px-2 py-0.5 rounded-full text-xs font-bold ${
                item.status === 'Resulted' ? 'bg-green-100 text-green-700' : 'bg-slate-100 text-slate-600'
              }`}>{item.status}</span>
            </div>

            {item.lab_tests?.flatMap((t: any) => t.lab_results ?? []).map((result: any) => (
              <div key={result.id} className="px-6 py-4">
                {result.result_value && (
                  <div className="flex items-center gap-4 mb-3 pb-3 border-b border-slate-50">
                    <div>
                      <p className="text-xs text-slate-500 uppercase tracking-wide font-semibold">Overall</p>
                      <p className="text-xl font-bold text-slate-900">{result.result_value} <span className="text-sm text-slate-400">{result.unit}</span></p>
                      {result.reference_range && <p className="text-xs text-slate-400">Ref: {result.reference_range}</p>}
                    </div>
                    <FlagDisplay flag={result.abnormal_flag} />
                  </div>
                )}

                {result.lab_result_parameters?.length > 0 && (
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="text-slate-500 text-xs uppercase tracking-wide border-b border-slate-100">
                        <th className="py-2 text-left font-semibold">Parameter</th>
                        <th className="py-2 text-left font-semibold">Value</th>
                        <th className="py-2 text-left font-semibold">Unit</th>
                        <th className="py-2 text-left font-semibold">Ref. Range</th>
                        <th className="py-2 text-left font-semibold">Flag</th>
                      </tr>
                    </thead>
                    <tbody>
                      {result.lab_result_parameters.map((p: any) => (
                        <tr key={p.id} className={`border-b border-slate-50 ${p.abnormal_flag !== 'Normal' ? 'bg-red-50/30' : ''}`}>
                          <td className="py-2 font-medium text-slate-700">{p.parameter_name}</td>
                          <td className={`py-2 font-bold ${p.abnormal_flag !== 'Normal' ? 'text-red-700' : 'text-slate-800'}`}>{p.parameter_value ?? '—'}</td>
                          <td className="py-2 text-slate-500">{p.unit ?? '—'}</td>
                          <td className="py-2 text-slate-500">{p.reference_range ?? '—'}</td>
                          <td className="py-2"><FlagDisplay flag={p.abnormal_flag} /></td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                )}
              </div>
            ))}
          </div>
        ))}
      </div>
    </div>
  )
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex justify-between text-sm">
      <span className="text-slate-500">{label}</span>
      <span className="font-medium text-slate-800">{value}</span>
    </div>
  )
}

function FlagDisplay({ flag }: { flag: string }) {
  const Icon = FLAG_ICON[flag] ?? Minus
  const color = FLAG_COLOR[flag] ?? 'text-slate-500'
  return <span className={`inline-flex items-center gap-1 text-xs font-semibold ${color}`}><Icon className="w-3.5 h-3.5" />{flag}</span>
}
