import type { SupabaseClient } from '@supabase/supabase-js'
import { createSample } from '@/repositories/laboratory/sampleRepository'
import { labOrderService } from './labOrderService'

export const sampleService = {
  async collectSample(
    supabase: SupabaseClient,
    labOrderId: string,
    specimenType: string,
    userId: string
  ) {
    // 1. Create sample record (auto-barcode generated by DB trigger)
    const sample = await createSample(supabase, labOrderId, specimenType, userId)

    // 2. Advance order status -> 'Sample Collected'
    await labOrderService.advanceStatus(supabase, labOrderId, 'Sample Collected', userId, 'Sample collected')

    return sample
  }
}
